# Generated by Django 5.2.6 on 2025-09-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('file_blob', models.BinaryField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='embedding_blob',
            field=models.BinaryField(),
        ),
    ]
