# Generated by Django 5.2.6 on 2025-09-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0002_binaryfile_alter_student_embedding_blob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BinaryFile',
        ),
    ]
