# Generated by Django 5.2.6 on 2025-09-15 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0004_student_teacher_alter_student_embedding_blob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='No Teacher', max_length=10),
            preserve_default=False,
        ),
    ]
