# Generated by Django 5.2.6 on 2025-09-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0005_attendance_time_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.CharField(default='No Teacher', max_length=100),
            preserve_default=False,
        ),
    ]
