# Generated by Django 5.2.6 on 2025-09-16 16:56

import sih.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0008_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(default=sih.models.current_time),
        ),
    ]
