# Generated by Django 5.2.6 on 2025-09-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0009_alter_attendance_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='solletipranav@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
